apiVersion: v1
kind: Service
metadata:
  name: etims-service
  namespace: chatnation
  labels:
    app: etims-app
spec:
  selector:
    app: etims-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
